// <auto-generated />
using System;
using MagicVilla_VillaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_VillaAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_VillaAPI.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedDate")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "Pool, Wi-Fi",
                            CreatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7227),
                            Details = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            ImageUrl = "https://villascroatia.com/villas/modern-luxury-villa-with-pool-in-medulin",
                            LastUpdatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7229),
                            Name = "Royal Villa",
                            Occupancy = 5,
                            Rate = 200.0,
                            Sqft = 550
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "Beach Access, BBQ Area, Wi-Fi",
                            CreatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7238),
                            Details = "Enjoy the ocean breeze in this cozy villa by the beach, perfect for family vacations.",
                            ImageUrl = "https://unsplash.com/photos/villa-beachside",
                            LastUpdatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7238),
                            Name = "Beachside Villa",
                            Occupancy = 4,
                            Rate = 250.0,
                            Sqft = 450
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "Fireplace, Hiking Trails, Wi-Fi",
                            CreatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7239),
                            Details = "Surrounded by nature, this villa offers stunning mountain views and tranquility.",
                            ImageUrl = "https://pixabay.com/photos/mountain-villa-retreat",
                            LastUpdatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7239),
                            Name = "Mountain Retreat",
                            Occupancy = 6,
                            Rate = 300.0,
                            Sqft = 700
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "City View, Smart Home Features",
                            CreatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7241),
                            Details = "Located in the heart of the city, this modern villa features sleek interiors and convenience.",
                            ImageUrl = "https://luxuryurbanvilla.com",
                            LastUpdatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7241),
                            Name = "Urban Luxe",
                            Occupancy = 3,
                            Rate = 400.0,
                            Sqft = 350
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "Private Pool, Outdoor Shower, Wi-Fi",
                            CreatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7242),
                            Details = "Surrounded by lush greenery and exotic plants, this villa is a tropical dream come true.",
                            ImageUrl = "https://tropicalvillas.com/paradise",
                            LastUpdatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7242),
                            Name = "Tropical Paradise",
                            Occupancy = 5,
                            Rate = 350.0,
                            Sqft = 600
                        },
                        new
                        {
                            Id = 6,
                            Amenity = "Garden, Fireplace, Wi-Fi",
                            CreatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7243),
                            Details = "A rustic villa nestled in the countryside, perfect for a peaceful escape.",
                            ImageUrl = "https://pixabay.com/photos/countryside-villa",
                            LastUpdatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7244),
                            Name = "Countryside Charm",
                            Occupancy = 4,
                            Rate = 180.0,
                            Sqft = 500
                        },
                        new
                        {
                            Id = 7,
                            Amenity = "Lake View, Private Dock, Wi-Fi",
                            CreatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7245),
                            Details = "Relax by the water in this beautiful lakeside villa, ideal for a romantic getaway.",
                            ImageUrl = "https://lakesidevillas.com/haven",
                            LastUpdatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7245),
                            Name = "Lakeside Haven",
                            Occupancy = 2,
                            Rate = 275.0,
                            Sqft = 400
                        },
                        new
                        {
                            Id = 8,
                            Amenity = "Infinity Pool, Private Elevator, Wi-Fi",
                            CreatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7246),
                            Details = "Experience ultimate luxury in this spacious penthouse with panoramic city views.",
                            ImageUrl = "https://unsplash.com/photos/luxury-penthouse",
                            LastUpdatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7246),
                            Name = "Luxury Penthouse",
                            Occupancy = 4,
                            Rate = 500.0,
                            Sqft = 800
                        },
                        new
                        {
                            Id = 9,
                            Amenity = "Garden, Patio, Wi-Fi",
                            CreatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7248),
                            Details = "A charming and quaint cottage surrounded by picturesque gardens.",
                            ImageUrl = "https://pixabay.com/photos/cozy-cottage",
                            LastUpdatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7248),
                            Name = "Cozy Cottage",
                            Occupancy = 3,
                            Rate = 150.0,
                            Sqft = 300
                        },
                        new
                        {
                            Id = 10,
                            Amenity = "Private Pool, Outdoor Fireplace, Wi-Fi",
                            CreatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7249),
                            Details = "Stay in the serene beauty of this desert villa with breathtaking sunset views.",
                            ImageUrl = "https://desertoasisvillas.com",
                            LastUpdatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7249),
                            Name = "Desert Oasis",
                            Occupancy = 5,
                            Rate = 320.0,
                            Sqft = 650
                        },
                        new
                        {
                            Id = 11,
                            Amenity = "Infinity Pool, Outdoor Kitchen, Wi-Fi",
                            CreatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7250),
                            Details = "Disconnect and relax in this secluded jungle villa surrounded by nature.",
                            ImageUrl = "https://jungleescapevillas.com",
                            LastUpdatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7251),
                            Name = "Secluded Jungle Retreat",
                            Occupancy = 6,
                            Rate = 400.0,
                            Sqft = 750
                        },
                        new
                        {
                            Id = 12,
                            Amenity = "Private Balcony, Infinity Pool, Wi-Fi",
                            CreatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7252),
                            Details = "Perched on a cliff, this villa offers spectacular ocean views and luxury living.",
                            ImageUrl = "https://pixabay.com/photos/cliffside-villa",
                            LastUpdatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7252),
                            Name = "Cliffside Haven",
                            Occupancy = 5,
                            Rate = 550.0,
                            Sqft = 700
                        },
                        new
                        {
                            Id = 13,
                            Amenity = "Private Beach, Water Sports Gear, Wi-Fi",
                            CreatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7253),
                            Details = "Your own private island getaway with pristine beaches and crystal-clear waters.",
                            ImageUrl = "https://unsplash.com/photos/island-hideaway",
                            LastUpdatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7253),
                            Name = "Island Hideaway",
                            Occupancy = 8,
                            Rate = 1200.0,
                            Sqft = 1000
                        },
                        new
                        {
                            Id = 14,
                            Amenity = "Wine Cellar, Vineyard Tours, Wi-Fi",
                            CreatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7254),
                            Details = "Stay amidst lush vineyards in this charming villa with a rustic touch.",
                            ImageUrl = "https://vineyardvillas.com",
                            LastUpdatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7254),
                            Name = "Vintage Vineyard Villa",
                            Occupancy = 4,
                            Rate = 300.0,
                            Sqft = 500
                        },
                        new
                        {
                            Id = 15,
                            Amenity = "Ski-In/Ski-Out Access, Fireplace, Wi-Fi",
                            CreatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7256),
                            Details = "A cozy and warm chalet perfect for ski trips and winter getaways.",
                            ImageUrl = "https://pixabay.com/photos/snowy-chalet",
                            LastUpdatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7256),
                            Name = "Snowy Chalet",
                            Occupancy = 6,
                            Rate = 450.0,
                            Sqft = 600
                        },
                        new
                        {
                            Id = 16,
                            Amenity = "Terrace, Olive Garden, Wi-Fi",
                            CreatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7257),
                            Details = "A sunny villa inspired by Mediterranean architecture and lifestyle.",
                            ImageUrl = "https://mediterraneanvillas.com",
                            LastUpdatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7257),
                            Name = "Mediterranean Escape",
                            Occupancy = 5,
                            Rate = 280.0,
                            Sqft = 550
                        },
                        new
                        {
                            Id = 17,
                            Amenity = "Ocean View, Onboard Chef, Wi-Fi",
                            CreatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7258),
                            Details = "Enjoy luxury on the water with this unique yacht villa experience.",
                            ImageUrl = "https://unsplash.com/photos/yacht-villa",
                            LastUpdatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7258),
                            Name = "Luxury Yacht Villa",
                            Occupancy = 2,
                            Rate = 1000.0,
                            Sqft = 300
                        },
                        new
                        {
                            Id = 18,
                            Amenity = "Banquet Hall, Swimming Pool, Wi-Fi",
                            CreatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7260),
                            Details = "A grand estate in the countryside, perfect for large gatherings and events.",
                            ImageUrl = "https://pixabay.com/photos/countryside-estate",
                            LastUpdatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7260),
                            Name = "Countryside Estate",
                            Occupancy = 12,
                            Rate = 1500.0,
                            Sqft = 2000
                        },
                        new
                        {
                            Id = 19,
                            Amenity = "Antique Furnishings, Garden, Wi-Fi",
                            CreatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7261),
                            Details = "Step back in time with this historic villa featuring antique decor and charm.",
                            ImageUrl = "https://historicmanorvillas.com",
                            LastUpdatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7261),
                            Name = "Historic Manor",
                            Occupancy = 8,
                            Rate = 600.0,
                            Sqft = 850
                        },
                        new
                        {
                            Id = 20,
                            Amenity = "Solar Power, Organic Garden, Wi-Fi",
                            CreatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7262),
                            Details = "A sustainable and eco-friendly villa offering modern comforts in nature.",
                            ImageUrl = "https://ecovillas.com",
                            LastUpdatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7262),
                            Name = "Eco-Friendly Retreat",
                            Occupancy = 4,
                            Rate = 220.0,
                            Sqft = 500
                        });
                });

            modelBuilder.Entity("MagicVilla_VillaAPI.Models.VillaNumber", b =>
                {
                    b.Property<int>("Code")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("LastUpdatedDate")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("SpecialDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VillaID")
                        .HasColumnType("int");

                    b.HasKey("Code");

                    b.HasIndex("VillaID");

                    b.ToTable("VillaNumbers");

                    b.HasData(
                        new
                        {
                            Code = 101,
                            CreatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7359),
                            LastUpdatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7359),
                            SpecialDetails = "Near the lake",
                            VillaID = 1
                        },
                        new
                        {
                            Code = 102,
                            CreatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7362),
                            LastUpdatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7363),
                            SpecialDetails = "Close to the city center",
                            VillaID = 2
                        },
                        new
                        {
                            Code = 103,
                            CreatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7363),
                            LastUpdatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7363),
                            SpecialDetails = "Next to the park",
                            VillaID = 3
                        },
                        new
                        {
                            Code = 104,
                            CreatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7364),
                            LastUpdatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7364),
                            SpecialDetails = "Near the mountains",
                            VillaID = 4
                        },
                        new
                        {
                            Code = 105,
                            CreatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7365),
                            LastUpdatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7365),
                            SpecialDetails = "Seaside view",
                            VillaID = 5
                        },
                        new
                        {
                            Code = 106,
                            CreatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7366),
                            LastUpdatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7366),
                            SpecialDetails = "Private forest access",
                            VillaID = 6
                        },
                        new
                        {
                            Code = 107,
                            CreatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7367),
                            LastUpdatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7367),
                            SpecialDetails = "Adjacent to the golf course",
                            VillaID = 7
                        },
                        new
                        {
                            Code = 108,
                            CreatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7367),
                            LastUpdatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7368),
                            SpecialDetails = "Near the historic district",
                            VillaID = 8
                        },
                        new
                        {
                            Code = 109,
                            CreatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7368),
                            LastUpdatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7368),
                            SpecialDetails = "In the vineyard area",
                            VillaID = 9
                        },
                        new
                        {
                            Code = 110,
                            CreatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7369),
                            LastUpdatedDate = new DateTime(2025, 3, 9, 13, 35, 46, 189, DateTimeKind.Utc).AddTicks(7369),
                            SpecialDetails = "Close to the airport",
                            VillaID = 10
                        });
                });

            modelBuilder.Entity("MagicVilla_VillaAPI.Models.VillaNumber", b =>
                {
                    b.HasOne("MagicVilla_VillaAPI.Models.Villa", "Villa")
                        .WithMany()
                        .HasForeignKey("VillaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });
#pragma warning restore 612, 618
        }
    }
}
