parameters:
  - name: appName
    type: string

  - name: packageName
    type: string



stages:
- stage:
  displayName: Deploy ${{ parameters.appName }}

  jobs:
  - deployment: 
    displayName: Deploy to ${{ parameters.environment }}
    environment: ${{ parameters.environment }}
    pool:
      vmImage: 'ubuntu-latest'

    strategy:
      runOnce:
        deploy:

          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy ${{ appName }} to azure'
            inputs:
              azureSubscription: 'zakaria-ali-personal'
              appType: 'webAppLinux'
              appName: ${{ parameters.appName }}
              package: '$(Pipeline.Workspace)/drop1/*.zip'